### ISSUE TITLE
How to extract the audio files

### ISSUE THREAD

**Issue by Cyronlee** [IronBit-0/AnimaleseSynthesis#1]
Could you please tell me how to extract the audio files?
I wanna make a Chinese version of this.
Thanks!

**Comment by IronBit-0** [comment]
I don't know how to extract the audio files from the game or the game files, but members of the [Animal Crossing New Horizons Discord](https://discordapp.com/invite/acnh) have already done that and put the files in [this Google Drive.](https://drive.google.com/drive/u/0/folders/1gbxYGGkeyJWTk-QSBw-quzobxbPQgSpW) The files are under Effects>Keyboard. You may need to edit the code for it to be compatible with other languages.

**Comment by Cyronlee** [comment]
Awesome!
Thanks again
